"use client"

import React, { useState, useRef } from "react"
import { Input } from "@/components/ui/input"
import { motion, AnimatePresence } from "framer-motion"
import {
  Download,
  Copy,
  Loader2,
  Check,
  Code2,
  Zap,
  FileCode,
  Eye,
  EyeOff,
  ChevronDown,
  ChevronUp,
  Settings,
  Film
} from "lucide-react"
import type { Layer } from "@/types"
import { useToast } from "@/components/toast-system"

interface CodePanelProps {
  code?: string
  onGenerateCode?: (optimize?: boolean) => Promise<void>
  onShowElementSettings?: () => void
  isGenerating?: boolean
  settings?: {
    particleCount: number
    shapeSize: number
    color: string
    particle: string
    alpha: number
    repeat: number
    yOffset: number
    skillName: string
    pngSize: number
    objScale: number
    performanceMode: boolean
    imageColorMode: boolean
    frameMode?: string
    frameCount?: number
  }
  onSettingsChange?: (settings: any) => void
  layers?: Layer[]
  onUpdateLayer?: (layerId: string, updates: Partial<Layer>) => void
  currentLayer?: Layer | null
  modes?: {
    rotateMode: boolean
    rainbowMode: boolean
    riseMode: boolean
    performanceMode: boolean
    localRotateMode: boolean
    moveMode: boolean
    proximityMode: boolean
    staticRainbowMode?: boolean
  }
  onFrameSettingsChange?: (mode: "auto" | "manual", frameCount?: number) => void
  optimize?: boolean
  setOptimize?: (v: boolean) => void
}

// Clean code function - removes advertisement comments and all comments for preview
function cleanCode(code: string, removeAllComments: boolean = false): string {
  if (!code) return ""

  const lines = code.split('\n')
  const cleanedLines = lines.filter(line => {
    const trimmed = line.trim()

    if (removeAllComments) {
      // Remove all comment lines for preview
      if (trimmed.startsWith('#')) {
        return false
      }
    } else {
      // Remove only advertisement comments for copy/download
      if (trimmed.startsWith('#') && (
        trimmed.includes('AuraFX') ||
        trimmed.includes('discord.gg') ||
        trimmed.includes('Generated by') ||
        trimmed.includes('Visit') ||
        trimmed.includes('Support')
      )) {
        return false
      }
    }
    return true
  })

  return cleanedLines.join('\n')
}

// Virtual Scrolling Code Display Component
function CompactCodeDisplay({ code, isVisible }: { code: string; isVisible: boolean }) {
  const cleanedCode = cleanCode(code, true) // Remove ALL comments for preview
  const allLines = cleanedCode.split("\n").filter(line => line.trim()) // Remove empty lines too
  
  const [scrollTop, setScrollTop] = useState(0)
  const containerRef = useRef<HTMLDivElement>(null)
  
  // Virtual scrolling parameters
  const LINE_HEIGHT = 16 // Height of each line in pixels
  const CONTAINER_HEIGHT = 320 - 40 // Total height minus header
  const VISIBLE_LINES = Math.ceil(CONTAINER_HEIGHT / LINE_HEIGHT)
  const BUFFER_SIZE = 10 // Extra lines to render for smooth scrolling
  
  // Calculate which lines to render
  const startIndex = Math.max(0, Math.floor(scrollTop / LINE_HEIGHT) - BUFFER_SIZE)
  const endIndex = Math.min(allLines.length, startIndex + VISIBLE_LINES + (BUFFER_SIZE * 2))
  const visibleLines = allLines.slice(startIndex, endIndex)
  
  // Total height for scrollbar
  const totalHeight = allLines.length * LINE_HEIGHT
  
  const handleScroll = (e: React.UIEvent<HTMLDivElement>) => {
    setScrollTop(e.currentTarget.scrollTop)
  }

  if (!isVisible) {
    return (
      <div className="h-full flex items-center justify-center bg-gray-50 rounded-lg border border-gray-200">
        <div className="text-center space-y-1">
          <EyeOff className="w-6 h-6 text-gray-400 mx-auto" />
          <p className="text-xs text-gray-500">Preview hidden</p>
        </div>
      </div>
    )
  }

  return (
    <div className="h-80 flex flex-col bg-white rounded-lg border border-gray-200 overflow-hidden">
      {/* Compact Header */}
      <div className="flex-shrink-0 px-3 py-2 bg-gray-50 border-b border-gray-200 flex items-center justify-between">
        <div className="flex items-center gap-2">
          <div className="flex gap-1">
            <div className="w-2 h-2 rounded-full bg-gray-300" />
            <div className="w-2 h-2 rounded-full bg-gray-300" />
            <div className="w-2 h-2 rounded-full bg-gray-300" />
          </div>
          <span className="text-xs font-mono text-gray-600">effect.yaml</span>
        </div>
        <span className="text-[10px] text-gray-500">{allLines.length} lines</span>
      </div>

      {/* Virtual Scrolling Code Content */}
      <div 
        ref={containerRef}
        className="flex-1 overflow-auto compact-scrollbar"
        onScroll={handleScroll}
      >
        <div style={{ height: totalHeight, position: 'relative' }}>
          <div 
            style={{ 
              position: 'absolute',
              top: startIndex * LINE_HEIGHT,
              width: '100%'
            }}
            className="font-mono text-[10px] leading-tight min-w-max"
          >
            {visibleLines.map((line, index) => {
              const actualIndex = startIndex + index
              return (
                <div 
                  key={actualIndex} 
                  className="flex hover:bg-gray-50 transition-colors min-w-max"
                  style={{ height: LINE_HEIGHT }}
                >
                  <span className="flex-shrink-0 text-gray-400 text-right px-2 py-0.5 select-none w-8 bg-gray-50/50">
                    {actualIndex + 1}
                  </span>
                  <span className="px-2 py-0.5 text-gray-700 whitespace-nowrap">
                    {line || " "}
                  </span>
                </div>
              )
            })}
          </div>
        </div>
      </div>

      <style jsx>{`
        .compact-scrollbar::-webkit-scrollbar {
          width: 6px;
          height: 6px;
        }
        .compact-scrollbar::-webkit-scrollbar-track {
          background: #ffffff;
        }
        .compact-scrollbar::-webkit-scrollbar-thumb {
          background: #e5e7eb;
          border-radius: 3px;
        }
        .compact-scrollbar::-webkit-scrollbar-thumb:hover {
          background: #d1d5db;
        }
        .compact-scrollbar::-webkit-scrollbar-corner {
          background: #ffffff;
        }
      `}</style>
    </div>
  )
}

export function CodePanel({
  code = "",
  onGenerateCode = async () => { },
  isGenerating = false,
  settings = {
    particleCount: 100,
    shapeSize: 1,
    color: "#ff6b35",
    particle: "reddust",
    alpha: 10,
    repeat: 1,
    yOffset: 0,
    skillName: "MyEffect",
    pngSize: 100,
    objScale: 1,
    performanceMode: false,
    imageColorMode: false,
    frameMode: "auto",
    frameCount: 60
  },
  onSettingsChange = () => { },
  modes = {
    rotateMode: false,
    rainbowMode: false,
    riseMode: false,
    performanceMode: false,
    localRotateMode: false,
    moveMode: false,
    proximityMode: false,
    staticRainbowMode: false
  },
  onFrameSettingsChange = () => { },
  optimize = false,
  setOptimize = () => { }
}: CodePanelProps) {
  const [copied, setCopied] = useState(false)
  const [showCode, setShowCode] = useState(true)
  const [settingsExpanded, setSettingsExpanded] = useState(true)
  const [framesExpanded, setFramesExpanded] = useState(true)
  const [codePreviewExpanded, setCodePreviewExpanded] = useState(true)
  const [frameMode, setFrameMode] = useState<"auto" | "manual">("auto")
  const [manualFrameCount, setManualFrameCount] = useState(120)
  const { toast } = useToast()

  // Check if any animation modes are active
  const hasAnimationModes = Object.values(modes).some(Boolean)

  const handleCopy = async () => {
    try {
      const cleanedCode = cleanCode(code, false) // Keep comments for copy
      await navigator.clipboard.writeText(cleanedCode)
      setCopied(true)
      toast({
        title: "Copied!",
        description: "Code copied to clipboard",
        duration: 2000,
      })
      setTimeout(() => setCopied(false), 2000)
    } catch (error) {
      toast({
        title: "Error",
        description: "Failed to copy code",
        variant: "destructive",
        duration: 2000,
      })
    }
  }

  const handleDownload = () => {
    const cleanedCode = cleanCode(code, false) // Keep comments for download
    const blob = new Blob([cleanedCode], { type: "text/yaml" })
    const url = URL.createObjectURL(blob)
    const a = document.createElement("a")
    a.href = url
    a.download = `${settings.skillName || "effect"}.yaml`
    a.click()
    URL.revokeObjectURL(url)
    toast({
      title: "Downloaded",
      description: `Effect saved as ${settings.skillName || "effect"}.yaml`,
      duration: 2000,
    })
  }

  const handleGenerate = async () => {
    await onGenerateCode(optimize)
  }

  const handleFrameModeChange = (mode: "auto" | "manual") => {
    setFrameMode(mode)
    onFrameSettingsChange(mode, mode === "manual" ? manualFrameCount : undefined)
  }

  const handleManualFrameChange = (value: number) => {
    setManualFrameCount(value)
    if (frameMode === "manual") {
      onFrameSettingsChange("manual", value)
    }
  }

  return (
    <div className="h-full w-full bg-white flex flex-col text-sm">
      {/* Generate Code Section - Tools Panel Style */}
      <div className="flex-shrink-0 border-b border-gray-200">
        <div className="px-4 py-2 text-xs font-semibold text-gray-500 uppercase tracking-wider">Code Generator</div>
        <div className="p-4">
          <motion.button
            whileHover={{ scale: 1.02 }}
            whileTap={{ scale: 0.98 }}
            onClick={handleGenerate}
            disabled={isGenerating}
            className="w-full py-3 px-4 bg-blue-600 hover:bg-blue-700 disabled:bg-gray-400 text-white font-medium rounded-lg transition-all duration-200 flex items-center justify-center gap-2"
          >
            {isGenerating ? (
              <>
                <Loader2 className="w-4 h-4 animate-spin" />
                Generating...
              </>
            ) : (
              <>
                <Zap className="w-4 h-4" />
                Generate Code
              </>
            )}
          </motion.button>
        </div>
      </div>

      {/* Settings Section - Tools Panel Style */}
      <div className="flex-shrink-0 border-b border-gray-200">
        <button
          onClick={() => setSettingsExpanded(!settingsExpanded)}
          className="w-full flex items-center justify-between px-4 py-2 text-xs font-semibold text-gray-500 uppercase tracking-wider hover:bg-gray-50"
        >
          <span>Settings</span>
          {settingsExpanded ? <ChevronUp className="w-3 h-3" /> : <ChevronDown className="w-3 h-3" />}
        </button>
        <AnimatePresence>
          {settingsExpanded && (
            <motion.div
              initial={{ height: 0, opacity: 0 }}
              animate={{ height: "auto", opacity: 1 }}
              exit={{ height: 0, opacity: 0 }}
              transition={{ duration: 0.3, ease: "easeInOut" }}
              className="overflow-hidden"
            >
              <div className="p-4 space-y-4">
                {/* Skill Name */}
                <div>
                  <label className="text-xs font-semibold text-gray-600 uppercase tracking-wider">Skill Name</label>
                  <div className="mt-2">
                    <Input
                      type="text"
                      value={settings.skillName}
                      onChange={(e) => onSettingsChange({ ...settings, skillName: e.target.value })}
                      placeholder="Enter effect name..."
                      className="bg-white border-gray-300 text-gray-900 text-sm"
                    />
                  </div>
                </div>

                {/* Optimize Code Toggle */}
                <div className="flex items-center justify-between">
                  <span className="text-sm font-medium text-gray-700">Optimize Code</span>
                  <button
                    onClick={() => setOptimize(!optimize)}
                    className={`relative inline-flex h-5 w-9 items-center rounded-full transition-colors ${optimize ? 'bg-blue-600' : 'bg-gray-300'}`}
                  >
                    <span
                      className={`inline-block h-4 w-4 transform rounded-full bg-white transition-transform ${optimize ? 'translate-x-4' : 'translate-x-0.5'}`}
                    />
                  </button>
                </div>
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </div>

      {/* Animation Frames Section - Tools Panel Style */}
      <div className="flex-shrink-0 border-b border-gray-200">
        <button
          onClick={() => setFramesExpanded(!framesExpanded)}
          className="w-full flex items-center justify-between px-4 py-2 text-xs font-semibold text-gray-500 uppercase tracking-wider hover:bg-gray-50"
        >
          <span>Animation Frames</span>
          {framesExpanded ? <ChevronUp className="w-3 h-3" /> : <ChevronDown className="w-3 h-3" />}
        </button>
        <AnimatePresence>
          {framesExpanded && (
            <motion.div
              initial={{ height: 0, opacity: 0 }}
              animate={{ height: "auto", opacity: 1 }}
              exit={{ height: 0, opacity: 0 }}
              transition={{ duration: 0.3, ease: "easeInOut" }}
              className="overflow-hidden"
            >
              <div className="p-4 space-y-4">
                {/* Frame Mode Toggle - Tools Panel Style */}
                <div className="space-y-3">
                  <label className="text-xs font-semibold text-gray-600 uppercase tracking-wider">Frame Mode</label>
                  
                  {/* Toggle Buttons */}
                  <div className="flex gap-1 bg-gray-100 rounded-lg p-1">
                    <motion.button
                      onClick={() => handleFrameModeChange("auto")}
                      className={`flex-1 py-2 px-3 text-xs font-medium rounded-md transition-all duration-200 ${
                        frameMode === "auto"
                          ? "bg-white text-blue-700 shadow-sm"
                          : "text-gray-600 hover:text-gray-800"
                      }`}
                      whileHover={{ scale: frameMode === "auto" ? 1 : 1.02 }}
                      whileTap={{ scale: 0.98 }}
                    >
                      Auto
                    </motion.button>
                    
                    <motion.button
                      onClick={() => handleFrameModeChange("manual")}
                      className={`flex-1 py-2 px-3 text-xs font-medium rounded-md transition-all duration-200 ${
                        frameMode === "manual"
                          ? "bg-white text-blue-700 shadow-sm"
                          : "text-gray-600 hover:text-gray-800"
                      }`}
                      whileHover={{ scale: frameMode === "manual" ? 1 : 1.02 }}
                      whileTap={{ scale: 0.98 }}
                    >
                      Manual
                    </motion.button>
                  </div>
                </div>

                {/* Manual Frame Count - Tools Panel Style */}
                <AnimatePresence>
                  {frameMode === "manual" && (
                    <motion.div
                      initial={{ opacity: 0, height: 0 }}
                      animate={{ opacity: 1, height: "auto" }}
                      exit={{ opacity: 0, height: 0 }}
                      transition={{ duration: 0.2 }}
                      className="pl-4 border-l-2 border-blue-200 space-y-2"
                    >
                      <div className="flex items-center justify-between">
                        <label className="text-xs font-semibold text-gray-600 uppercase tracking-wider">Frame Count</label>
                        <span className="text-xs bg-gray-100 text-gray-700 px-2 py-1 rounded font-mono">
                          {manualFrameCount}
                        </span>
                      </div>
                      <input
                        type="range"
                        min={12}
                        max={240}
                        step={6}
                        value={manualFrameCount}
                        onChange={(e) => handleManualFrameChange(Number(e.target.value))}
                        className="w-full h-2 bg-gray-200 rounded-lg appearance-none cursor-pointer slider"
                      />
                      <div className="flex justify-between text-xs text-gray-400">
                        <span>12</span>
                        <span>240</span>
                      </div>
                    </motion.div>
                  )}
                </AnimatePresence>
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </div>

      {/* Code Preview Section - Tools Panel Style */}
      <div className="flex-1 overflow-y-auto scrollbar-hidden panel-container">
        <button
          onClick={() => setCodePreviewExpanded(!codePreviewExpanded)}
          className="w-full flex items-center justify-between px-4 py-2 text-xs font-semibold text-gray-500 uppercase tracking-wider hover:bg-gray-50"
        >
          <span>Code Preview</span>
          {codePreviewExpanded ? <ChevronUp className="w-3 h-3" /> : <ChevronDown className="w-3 h-3" />}
        </button>
        <AnimatePresence>
          {codePreviewExpanded && (
            <motion.div
              initial={{ height: 0, opacity: 0 }}
              animate={{ height: "auto", opacity: 1 }}
              exit={{ height: 0, opacity: 0 }}
              transition={{ duration: 0.3, ease: "easeInOut" }}
              className="overflow-hidden"
            >
              <div className="p-4 space-y-4">
                {/* Action Buttons */}
                <div className="flex gap-2">
                  <motion.button
                    whileHover={{ scale: 1.02 }}
                    whileTap={{ scale: 0.98 }}
                    onClick={() => setShowCode(!showCode)}
                    className={`flex-1 py-2 px-3 text-xs font-medium rounded-md transition-all duration-200 flex items-center justify-center gap-2 ${
                      showCode 
                        ? "bg-blue-50 text-blue-700 border border-blue-200" 
                        : "bg-gray-100 text-gray-600 hover:bg-gray-200"
                    }`}
                  >
                    {showCode ? <Eye className="w-3 h-3" /> : <EyeOff className="w-3 h-3" />}
                    {showCode ? "Hide" : "Show"}
                  </motion.button>
                  
                  <motion.button
                    whileHover={{ scale: 1.02 }}
                    whileTap={{ scale: 0.98 }}
                    onClick={handleCopy}
                    disabled={!code || isGenerating}
                    className="flex-1 py-2 px-3 text-xs font-medium rounded-md transition-all duration-200 flex items-center justify-center gap-2 bg-gray-100 text-gray-600 hover:bg-gray-200 disabled:opacity-50"
                  >
                    {copied ? <Check className="w-3 h-3 text-green-600" /> : <Copy className="w-3 h-3" />}
                    Copy
                  </motion.button>
                  
                  <motion.button
                    whileHover={{ scale: 1.02 }}
                    whileTap={{ scale: 0.98 }}
                    onClick={handleDownload}
                    disabled={!code || isGenerating}
                    className="flex-1 py-2 px-3 text-xs font-medium rounded-md transition-all duration-200 flex items-center justify-center gap-2 bg-gray-100 text-gray-600 hover:bg-gray-200 disabled:opacity-50"
                  >
                    <Download className="w-3 h-3" />
                    Download
                  </motion.button>
                </div>

                {/* Code Display */}
                <CompactCodeDisplay code={code} isVisible={showCode} />
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </div>

      <style jsx>{`
        .scrollbar-hidden {
          scrollbar-width: none; /* Firefox */
          -ms-overflow-style: none; /* IE and Edge */
        }
        .scrollbar-hidden::-webkit-scrollbar {
          display: none; /* Chrome, Safari, Opera */
          width: 0;
          height: 0;
        }
        .slider::-webkit-slider-thumb {
          appearance: none;
          height: 16px;
          width: 16px;
          border-radius: 50%;
          background: #3b82f6;
          cursor: pointer;
          border: 2px solid #ffffff;
          box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }
        .slider::-moz-range-thumb {
          height: 16px;
          width: 16px;
          border-radius: 50%;
          background: #3b82f6;
          cursor: pointer;
          border: 2px solid #ffffff;
          box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }
      `}</style>
    </div>
  )
}