"use client"

import React, { useState, useEffect } from "react"
import { Button } from "@/components/ui/button"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Switch } from "@/components/ui/switch"
import { motion, AnimatePresence } from "framer-motion"
import {
  Download,
  Copy,
  Loader2,
  Sparkles,
  Check,
  Code2,
  Zap,
  FileCode,
  Eye,
  EyeOff,
  ChevronDown,
  ChevronUp,
  Play,
  Settings,
  Film
} from "lucide-react"
import type { Layer } from "@/types"
import { toast } from "@/components/ui/use-toast"

interface CodePanelProps {
  code?: string
  onGenerateCode?: (optimize?: boolean) => Promise<void>
  onShowElementSettings?: () => void
  isGenerating?: boolean
  settings?: {
    particleCount: number
    shapeSize: number
    color: string
    particle: string
    alpha: number
    repeat: number
    yOffset: number
    skillName: string
    pngSize: number
    objScale: number
    performanceMode: boolean
    imageColorMode: boolean
    frameMode?: string
    frameCount?: number
  }
  onSettingsChange?: (settings: any) => void
  layers?: Layer[]
  onUpdateLayer?: (layerId: string, updates: Partial<Layer>) => void
  currentLayer?: Layer | null
  modes?: {
    rotateMode: boolean
    rainbowMode: boolean
    riseMode: boolean
    performanceMode: boolean
    localRotateMode: boolean
    moveMode: boolean
    proximityMode: boolean
    staticRainbowMode?: boolean
  }
  onFrameSettingsChange?: (mode: "auto" | "manual", frameCount?: number) => void
  optimize?: boolean
  setOptimize?: (v: boolean) => void
}

// Clean code function - removes advertisement comments and all comments for preview
function cleanCode(code: string, removeAllComments: boolean = false): string {
  if (!code) return ""

  const lines = code.split('\n')
  const cleanedLines = lines.filter(line => {
    const trimmed = line.trim()

    if (removeAllComments) {
      // Remove all comment lines for preview
      if (trimmed.startsWith('#')) {
        return false
      }
    } else {
      // Remove only advertisement comments for copy/download
      if (trimmed.startsWith('#') && (
        trimmed.includes('AuraFX') ||
        trimmed.includes('discord.gg') ||
        trimmed.includes('Generated by') ||
        trimmed.includes('Visit') ||
        trimmed.includes('Support')
      )) {
        return false
      }
    }
    return true
  })

  return cleanedLines.join('\n')
}

// Compact Code Display Component
function CompactCodeDisplay({ code, isVisible }: { code: string; isVisible: boolean }) {
  const cleanedCode = cleanCode(code, true) // Remove ALL comments for preview
  const lines = cleanedCode.split("\n").filter(line => line.trim()) // Remove empty lines too

  if (!isVisible) {
    return (
      <div className="h-64 flex items-center justify-center bg-gray-50 rounded-lg border border-gray-200">
        <div className="text-center space-y-1">
          <EyeOff className="w-6 h-6 text-gray-400 mx-auto" />
          <p className="text-xs text-gray-500">Preview hidden</p>
        </div>
      </div>
    )
  }

  return (
    <div className="h-64 flex flex-col bg-white rounded-lg border border-gray-200 overflow-hidden">
      {/* Compact Header */}
      <div className="flex-shrink-0 px-3 py-2 bg-gray-50 border-b border-gray-200 flex items-center justify-between">
        <div className="flex items-center gap-2">
          <div className="flex gap-1">
            <div className="w-2 h-2 rounded-full bg-gray-300" />
            <div className="w-2 h-2 rounded-full bg-gray-300" />
            <div className="w-2 h-2 rounded-full bg-gray-300" />
          </div>
          <span className="text-xs font-mono text-gray-600">effect.yaml</span>
        </div>
        <span className="text-[10px] text-gray-500">{lines.length} lines</span>
      </div>

      {/* Compact Code Content - Scrollable */}
      <div className="flex-1 overflow-auto compact-scrollbar">
        <div className="font-mono text-[10px] leading-tight">
          {lines.map((line, index) => (
            <div key={index} className="flex hover:bg-gray-50 transition-colors">
              <span className="flex-shrink-0 text-gray-400 text-right px-2 py-0.5 select-none w-8 bg-gray-50/50">
                {index + 1}
              </span>
              <span className="px-2 py-0.5 flex-1 text-gray-700 whitespace-pre">
                {line || " "}
              </span>
            </div>
          ))}
        </div>
      </div>

      <style jsx>{`
        .compact-scrollbar::-webkit-scrollbar {
          width: 4px;
        }
        .compact-scrollbar::-webkit-scrollbar-track {
          background: #f9fafb;
        }
        .compact-scrollbar::-webkit-scrollbar-thumb {
          background: #d1d5db;
          border-radius: 2px;
        }
        .compact-scrollbar::-webkit-scrollbar-thumb:hover {
          background: #9ca3af;
        }
      `}</style>
    </div>
  )
}

export function CodePanel({
  code = "",
  onGenerateCode = async () => { },
  isGenerating = false,
  settings = {
    particleCount: 100,
    shapeSize: 1,
    color: "#ff6b35",
    particle: "reddust",
    alpha: 10,
    repeat: 1,
    yOffset: 0,
    skillName: "MyEffect",
    pngSize: 100,
    objScale: 1,
    performanceMode: false,
    imageColorMode: false,
    frameMode: "auto",
    frameCount: 60
  },
  onSettingsChange = () => { },
  modes = {
    rotateMode: false,
    rainbowMode: false,
    riseMode: false,
    performanceMode: false,
    localRotateMode: false,
    moveMode: false,
    proximityMode: false,
    staticRainbowMode: false
  },
  onFrameSettingsChange = () => { },
  optimize = false,
  setOptimize = () => { }
}: CodePanelProps) {
  const [copied, setCopied] = useState(false)
  const [showCode, setShowCode] = useState(true)
  const [settingsExpanded, setSettingsExpanded] = useState(true)
  const [framesExpanded, setFramesExpanded] = useState(false)
  const [frameMode, setFrameMode] = useState<"auto" | "manual">("auto")
  const [manualFrameCount, setManualFrameCount] = useState(120)

  // Check if any animation modes are active
  const hasAnimationModes = Object.values(modes).some(Boolean)

  const handleCopy = async () => {
    try {
      const cleanedCode = cleanCode(code, false) // Keep comments for copy
      await navigator.clipboard.writeText(cleanedCode)
      setCopied(true)
      toast({
        title: "Copied!",
        description: "Code copied to clipboard",
        duration: 2000,
      })
      setTimeout(() => setCopied(false), 2000)
    } catch (error) {
      toast({
        title: "Error",
        description: "Failed to copy code",
        variant: "destructive",
        duration: 2000,
      })
    }
  }

  const handleDownload = () => {
    const cleanedCode = cleanCode(code, false) // Keep comments for download
    const blob = new Blob([cleanedCode], { type: "text/yaml" })
    const url = URL.createObjectURL(blob)
    const a = document.createElement("a")
    a.href = url
    a.download = `${settings.skillName || "effect"}.yaml`
    a.click()
    URL.revokeObjectURL(url)
    toast({
      title: "Downloaded",
      description: `Effect saved as ${settings.skillName || "effect"}.yaml`,
      duration: 2000,
    })
  }

  const handleGenerate = async () => {
    await onGenerateCode(optimize)
  }

  const handleFrameModeChange = (mode: "auto" | "manual") => {
    setFrameMode(mode)
    onFrameSettingsChange(mode, mode === "manual" ? manualFrameCount : undefined)
  }

  const handleManualFrameChange = (value: number) => {
    setManualFrameCount(value)
    if (frameMode === "manual") {
      onFrameSettingsChange("manual", value)
    }
  }

  return (
    <div className="w-full max-w-md mx-auto h-full flex flex-col bg-white p-4 overflow-y-auto">
      {/* Header */}
      <div className="flex-shrink-0 mb-6">
        <div className="flex items-center gap-3">
          <Code2 className="w-5 h-5 text-gray-700" />
          <div>
            <h3 className="font-semibold text-gray-900 text-base">Code Generator</h3>
            <p className="text-sm text-gray-500">Configure and export your effect</p>
          </div>
        </div>
      </div>

      {/* Generate Button */}
      <div className="flex-shrink-0 mb-6">
        <motion.button
          whileHover={{ scale: 1.02 }}
          whileTap={{ scale: 0.98 }}
          onClick={handleGenerate}
          disabled={isGenerating}
          className="w-full py-3 px-4 bg-gray-900 hover:bg-gray-800 disabled:bg-gray-400 text-white font-medium rounded-lg transition-all duration-200 flex items-center justify-center gap-2"
        >
          {isGenerating ? (
            <>
              <Loader2 className="w-4 h-4 animate-spin" />
              Generating...
            </>
          ) : (
            <>
              <Zap className="w-4 h-4" />
              Generate Code
            </>
          )}
        </motion.button>
      </div>

      {/* Settings Section */}
      <div className="flex-shrink-0 mb-6">
        <motion.button
          whileHover={{ scale: 1.01 }}
          whileTap={{ scale: 0.99 }}
          onClick={() => setSettingsExpanded(!settingsExpanded)}
          className="w-full flex items-center justify-between p-3 rounded-lg border border-gray-200 bg-white hover:bg-gray-50 transition-colors mb-3"
        >
          <div className="flex items-center gap-3">
            <div className="w-8 h-8 rounded-lg bg-gray-100 border border-gray-200 flex items-center justify-center">
              <Settings className="w-4 h-4 text-gray-600" />
            </div>
            <div className="text-left">
              <h4 className="text-sm font-semibold text-gray-900">Settings</h4>
              <p className="text-xs text-gray-500">Effect configuration</p>
            </div>
          </div>
          <motion.div
            animate={{ rotate: settingsExpanded ? 180 : 0 }}
            transition={{ duration: 0.2 }}
          >
            <ChevronDown className="h-4 w-4 text-gray-400" />
          </motion.div>
        </motion.button>

        <AnimatePresence>
          {settingsExpanded && (
            <motion.div
              initial={{ opacity: 0, height: 0 }}
              animate={{ opacity: 1, height: "auto" }}
              exit={{ opacity: 0, height: 0 }}
              transition={{ duration: 0.3, ease: "easeOut" }}
              className="overflow-hidden"
            >
              <div className="space-y-4 p-4 bg-gray-50 rounded-lg border border-gray-200">
                {/* Skill Name */}
                <div className="space-y-2">
                  <Label className="text-sm font-medium text-gray-700">Skill Name</Label>
                  <Input
                    type="text"
                    value={settings.skillName}
                    onChange={(e) => onSettingsChange({ ...settings, skillName: e.target.value })}
                    placeholder="Enter effect name..."
                    className="bg-white border-gray-200 text-gray-900"
                  />
                </div>

                {/* Optimizer */}
                <div className="flex items-center justify-between p-3 bg-white rounded-lg border border-gray-200">
                  <div className="flex items-center gap-3">
                    <Sparkles className="w-4 h-4 text-gray-600" />
                    <div>
                      <div className="flex items-center gap-2">
                        <span className="text-sm font-medium text-gray-900">Code Optimizer</span>
                        <span className="text-xs bg-gray-100 text-gray-700 px-2 py-0.5 rounded-full font-medium">BETA</span>
                      </div>
                      <p className="text-xs text-gray-500">Optimizes circle patterns</p>
                    </div>
                  </div>
                  <Switch
                    checked={optimize}
                    onCheckedChange={setOptimize}
                  />
                </div>
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </div>

      {/* Animation Frames Section */}
      {hasAnimationModes && (
        <div className="flex-shrink-0 mb-6">
          <motion.button
            whileHover={{ scale: 1.01 }}
            whileTap={{ scale: 0.99 }}
            onClick={() => setFramesExpanded(!framesExpanded)}
            className="w-full flex items-center justify-between p-3 rounded-lg border border-gray-200 bg-white hover:bg-gray-50 transition-colors mb-3"
          >
            <div className="flex items-center gap-3">
              <div className="w-8 h-8 rounded-lg bg-gray-100 border border-gray-200 flex items-center justify-center">
                <Film className="w-4 h-4 text-gray-600" />
              </div>
              <div className="text-left">
                <h4 className="text-sm font-semibold text-gray-900">Animation Frames</h4>
                <p className="text-xs text-gray-500">Frame configuration</p>
              </div>
            </div>
            <motion.div
              animate={{ rotate: framesExpanded ? 180 : 0 }}
              transition={{ duration: 0.2 }}
            >
              <ChevronDown className="h-4 w-4 text-gray-400" />
            </motion.div>
          </motion.button>

          <AnimatePresence>
            {framesExpanded && (
              <motion.div
                initial={{ opacity: 0, height: 0 }}
                animate={{ opacity: 1, height: "auto" }}
                exit={{ opacity: 0, height: 0 }}
                transition={{ duration: 0.3, ease: "easeOut" }}
                className="overflow-hidden"
              >
                <div className="space-y-4 p-4 bg-gray-50 rounded-lg border border-gray-200">
                  {/* Frame Mode Selection */}
                  <div className="space-y-3">
                    <Label className="text-sm font-medium text-gray-700">Frame Mode</Label>
                    <div className="grid grid-cols-2 gap-2">
                      <button
                        onClick={() => handleFrameModeChange("auto")}
                        className={`p-3 rounded-lg border transition-all text-sm font-medium ${frameMode === "auto"
                          ? "border-gray-300 bg-gray-100 text-gray-900"
                          : "border-gray-200 bg-white text-gray-700 hover:bg-gray-50"
                          }`}
                      >
                        Auto
                      </button>
                      <button
                        onClick={() => handleFrameModeChange("manual")}
                        className={`p-3 rounded-lg border transition-all text-sm font-medium ${frameMode === "manual"
                          ? "border-gray-300 bg-gray-100 text-gray-900"
                          : "border-gray-200 bg-white text-gray-700 hover:bg-gray-50"
                          }`}
                      >
                        Manual
                      </button>
                    </div>
                  </div>

                  {/* Manual Frame Count */}
                  {frameMode === "manual" && (
                    <div className="space-y-2">
                      <div className="flex items-center justify-between">
                        <Label className="text-sm font-medium text-gray-700">Frame Count</Label>
                        <span className="text-xs text-gray-500">{manualFrameCount}</span>
                      </div>
                      <input
                        type="range"
                        min={12}
                        max={240}
                        step={6}
                        value={manualFrameCount}
                        onChange={(e) => handleManualFrameChange(Number(e.target.value))}
                        className="w-full h-2 bg-gray-200 rounded-full appearance-none cursor-pointer slider-modern"
                      />
                    </div>
                  )}
                </div>
              </motion.div>
            )}
          </AnimatePresence>
        </div>
      )}

      {/* Code Preview Section */}
      <div className="flex-1 flex flex-col">
        <div className="flex items-center justify-between mb-3">
          <div className="flex items-center gap-2">
            <FileCode className="w-4 h-4 text-gray-600" />
            <span className="text-sm font-medium text-gray-900">Code Preview</span>
          </div>
          <div className="flex items-center gap-2">
            <motion.button
              whileHover={{ scale: 1.05 }}
              whileTap={{ scale: 0.95 }}
              onClick={() => setShowCode(!showCode)}
              className="p-2 rounded-lg border border-gray-200 bg-white hover:bg-gray-50 transition-colors"
            >
              {showCode ? <Eye className="w-4 h-4 text-gray-600" /> : <EyeOff className="w-4 h-4 text-gray-600" />}
            </motion.button>
            <motion.button
              whileHover={{ scale: 1.05 }}
              whileTap={{ scale: 0.95 }}
              onClick={handleCopy}
              disabled={!code || isGenerating}
              className="p-2 rounded-lg border border-gray-200 bg-white hover:bg-gray-50 transition-colors disabled:opacity-50"
            >
              {copied ? <Check className="w-4 h-4 text-green-600" /> : <Copy className="w-4 h-4 text-gray-600" />}
            </motion.button>
            <motion.button
              whileHover={{ scale: 1.05 }}
              whileTap={{ scale: 0.95 }}
              onClick={handleDownload}
              disabled={!code || isGenerating}
              className="p-2 rounded-lg border border-gray-200 bg-white hover:bg-gray-50 transition-colors disabled:opacity-50"
            >
              <Download className="w-4 h-4 text-gray-600" />
            </motion.button>
          </div>
        </div>

        {/* Code Display */}
        <div className="flex-1">
          <CompactCodeDisplay code={code} isVisible={showCode} />
        </div>
      </div>
    </div>
  )
}